### ISSUE TITLE
Protected function causing server crash

### ISSUE THREAD

**Issue by randallm** [mixmaxhq/arena#19]
@chuym We currently protect a number of Bull built-ins when instantiating our Bull interface (https://github.com/mixmaxhq/arena/blob/master/src/server/bull/index.js#L47).

One of these methods, `updateDelayTimer`, can sometimes cause a server crash:

```
Error: This function is protected !
    at Queue.protectFunction (/Users/randall/Workspace/arena/src/server/bull/index.js:10:9)
    at RedisClient.<anonymous> (/Users/randall/Workspace/arena/node_modules/bull/lib/queue.js:146:13)
    at emitTwo (events.js:106:13)
    at RedisClient.emit (events.js:194:7)
    at return_pub_sub (/Users/randall/Workspace/arena/node_modules/redis/index.js:781:18)
    at RedisClient.return_reply (/Users/randall/Workspace/arena/node_modules/redis/index.js:828:9)
    at JavascriptRedisParser.returnReply (/Users/randall/Workspace/arena/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/Users/randall/Workspace/arena/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/Users/randall/Workspace/arena/node_modules/redis/index.js:274:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
[nodemon] app crashed - waiting for file changes before starting...
```

because Bull expects this function to be available in its `guardianTimer` check (https://github.com/OptimalBits/bull/blob/v1.1.3/lib/queue.js#L229).

Although it is possible through a hack using the [non-standard `Function.caller`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/caller) property to selectively allow these functions to be called depending on their callers, I think it would be better to remove function protection altogether. I also share the concern that some of these functions should not be called by the module (like `updateDelayTimer`, for example), but I don't think this will be a problem for us as long as we make sure no unnecessary destructive actions are added in the future.

Thoughts?

**Comment by chuym** [comment]
Yeah, the reason why I added the protected functions mechanism is to prevent destructive actions to be called by mistake within the module but we should definitely make it less restrictive.

Let's just remove it 👍
